### ISSUE TITLE
nvim-treesitter.ts_utils.get_node_text is deprecated: use vim.treesitter.query.get_node_text

### ISSUE THREAD

**Issue by nyngwang** [romgrk/nvim-treesitter-context#111]
As title. The update https://github.com/nvim-treesitter/nvim-treesitter/commit/c3848e713a8272e524a7eabe9eb0897cf2d6932e seems to cause this.

**Comment by rockyzhang24** [comment]
Use this actively maintained fork https://github.com/lewis6991/nvim-treesitter-context

**Comment by nyngwang** [comment]
@rockyzhang24: Wow, thanks!
