### ISSUE TITLE
Cursor & screen movement feels slow in large files when context is enabled

### ISSUE THREAD

**Issue by romgrk** [romgrk/nvim-treesitter-context#13]
Consider strategies to reduce the delay, such as doing some work asynchronously or throttling the context update.

**Comment by dataO1** [comment]
In 500 lines of typescript i essentially cant move my cursor anymore, without waiting ~1 second for a redraw.

**Comment by romgrk** [comment]
Quite concerning. I'll try to investigate this issue in the next days.

**Comment by romgrk** [comment]
This has been fixed in https://github.com/romgrk/nvim-treesitter-context/commit/5130e4bb78a77a95815bcd5c7a434406e3283595. It was trying to highlight all the children of the contexted nodes, which isn't just the function/class name, it's all its content as well. There shouldn't be any more performance delays now, please re-open if it persists.

**Comment by dataO1** [comment]
works like a charm now :) thanks for the quick processing.
