### ISSUE TITLE
Issues when scrolling to the side and line is longer than width.

### ISSUE THREAD

**Issue by oberblastmeister** [romgrk/nvim-treesitter-context#16]
# Description

This plugin is really cool and works seamlessly with nvim-treesitter. However, when I scroll to the side, there are some issues. This mostly happens with the line is longer than the window and `nowrap` is set. When inserting from normal mode and the line is longer than the terminal window, inserting does not insert but the screen flashes and it inserts in the middle of the line. Typing text will not produce anything. When exiting out of insert mode, the cursor jumps back and the inserted text appears. Another issue is when side scrolling from the end of a line longer than the terminal width. The cursor should just scroll to the left but the whole window scrolls.

# Steps to reproduce

1. `set nowrap`
2. create a line that is longer than the window
3. go to the end of the line and click insert
4. the insert should not be at the correct place
5. type text
6. exit out of insert mode
7. the cursor should jump and the text will appear

# GIF

![Peek 2020-11-13 19-23](https://user-images.githubusercontent.com/61095988/99133004-45483d00-25e6-11eb-8ee0-7dee9febf95e.gif)

# Output of `nvim --version`

```
NVIM v0.5.0-828-g0a95549d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-abaca5c2-51e7-4cf1-bc06-8cf3e644ab24

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

(ps, as you can see I'm using barbar and it is really nice.)

**Comment by romgrk** [comment]
Ooooh, that's what it is. I was wondering why it was happening ^^

@seandewar do you think it could be yet another artifact of #12?

**Comment by seandewar** [comment]
Hi! I am able to reproduce this. :+1: 

Definitely related to #12.
The `getcurpos()` and `setpos()` approach we settled on isn't able to restore the window's scroll (_d'oh!_) after moving the cursor to the beginning of the line for the gutter width calculation.

>I think we should just disable context updating while in insert mode, what do you think?

This seems to sometimes break the normal mode horizontal scroll commands such as `zl` and `zL` too.

The correct way to fix this seems to be the `winsaveview()` and `winrestview()` approach shown earlier in that PR, though it would be nice if Vim had a way of doing this without the side-effects to begin with 😄 (though these functions exist as Vim's own workaround to problems like these).

**Comment by romgrk** [comment]
> it would be nice if Vim had a way of doing this without the side-effects to begin with

Vim is a horrible mess and I wonder why I still put up with this -_-

> I'll open a PR a bit later if needed.

Sure! I'm short on time these days so I'd be happy if you're down to work on this

**Comment by lucypero** [comment]
Sorry, what is the current state of this issue? I am still getting this bug

**Comment by romgrk** [comment]
The state of this issue was fixed. It is now not fixed. Let's keep the discussion in the new issue.
