### ISSUE TITLE
Bug:  some garbage shows when up last character of a file

### ISSUE THREAD

**Issue by cloggier** [romgrk/nvim-treesitter-context#20]
Great plugin, thanks a lot!

When I am on last character of the file I get some extra (I guess) floating window displayed, as per video below.

https://user-images.githubusercontent.com/69750637/103142991-c595ae00-470d-11eb-8365-b3e1cfe85f81.mov

Happens on `v0.5.0-dev+7b65a9135` with https://github.com/romgrk/nvim-treesitter-context/commit/192baea80c5b1a98a267eb7f13769f33adab7de8 (latest as of now).

**Comment by romgrk** [comment]
Can't reproduce. Can you give more details to reproduce?

Can you also run `echom map(nvim_list_wins(), {_,v -> nvim_win_get_config(v)})`?

**Comment by cloggier** [comment]
> Can't reproduce. Can you give more details to reproduce?

I have noticed that I don't have to be on last character of a file but rather on closing bracket/statement (`end` for lua, for instance) to trigger this behaviour. I have removed all my settings, auto commands, all other plugins and this is still happening. 

> Can you also run `echom map(nvim_list_wins(), {_,v -> nvim_win_get_config(v)})`?

When cursor is in position that displays context floating win:

```
[{'focusable': v:true, 'external': v:false, 'relative': ''}, {'focusable': v:false, 'col': 2.0, 'row': 0.0, 'relative': 'win', 'win': 1000, 'external': v:false, 'width': 176, 'height': 1, 'anchor': 'NW'}]
```

When it's not displayed:
```
[{'focusable': v:true, 'external': v:false, 'relative': ''}]
```

(Apologies for late response)

**Comment by romgrk** [comment]
And you're sure it's the context window there? It looks like it could be the statusline changing, because the context window is still at the top and the plugin only manages one window at a time, it never (afaik) creates more than one.

Could you run `call timer_start(1000, {->execute('let @+ = &stl | put')})` while the garbage is shown, and report the content of the statusline?

**Comment by cloggier** [comment]
Huge apologies for wasting your time, you were right, it's not your plugin!
```
 %#Search#∆%#Normal#%#Normal#local segment = %#MatchParen#{%<%#Normal#%{matchup#matchparen#scroll_update(20)}
```

Disabling that plugin fixes the problem. I am really not sure why it still was a problem during last tests when I disabled all my plugins.

**Comment by romgrk** [comment]
Yeeeah cool I have nothing to do then :laughing:
