### ISSUE TITLE
How can I change the background color?

### ISSUE THREAD

**Issue by weilbith** [romgrk/nvim-treesitter-context#29]
Well, there is not much to add to the title. :laughing:

**Comment by romgrk** [comment]
The popup uses the `NormalFloat` group as all other popups. It's not possible to configure this popup individually at the moment, but if it's something you're interested in, it's just a matter of setting `set winhl=Normal:CustomNormal` (or `nvim_win_set_option('winhl', 'Normal:CustomNormal')` in lua). I don't have much time these days but you can open a PR to add the option.
