### ISSUE TITLE
Show line number

### ISSUE THREAD

**Issue by romgrk** [romgrk/nvim-treesitter-context#37]
https://raw.githubusercontent.com/wellle/images/master/context-example.png

**Comment by zeertzjq** [comment]
I think one solution is to open one floating window for each line instead of one big floating window, and use something similar to the [offscreen floating window of vim-matchup](https://github.com/andymass/vim-matchup/blob/master/autoload/matchup/matchparen.vim).

**Comment by WhyNotHugo** [comment]
A floating window seems like a very neat choice and a great usage for one too.

**Comment by rockyzhang24** [comment]
Check this actively maintained fork https://github.com/lewis6991/nvim-treesitter-context
