### ISSUE TITLE
It doesn't seem to catch impl block in Rust

### ISSUE THREAD

**Issue by lucypero** [romgrk/nvim-treesitter-context#38]
When you are in a function inside an implementation in Rust, this doesn't show the `impl` line. It would be really helpful. `context.vim` also doesn't show it (only sometimes, it's weird)

**Comment by romgrk** [comment]
Either install [ts-playground](https://github.com/nvim-treesitter/playground) and tell me which groups are missing, or provide an example Rust source file with annotations where the missing groups are. Group names are things like `for_in_statement` or `function_declaration`.
