### ISSUE TITLE
Context floating window transferred to command-line window

### ISSUE THREAD

**Issue by jaekyeom** [romgrk/nvim-treesitter-context#44]
When the context floating window is open, pressing `q/`, `q?`, or `q:` opens the command-line window but with a floating window that displays the prior context, inside the command-line window.

**Comment by chardskarth** [comment]
How can I get this update? I'm still seeing this issue. I think everything's up to date. @romgrk 

![image](https://user-images.githubusercontent.com/26249511/195984338-a0fc4ebd-6e60-4be6-bcc1-7d5e9d731441.png)

**Comment by sxwpb** [comment]
same
