### ISSUE TITLE
CursorMoved Autocommands errors after clearing out buffers

### ISSUE THREAD

**Issue by petertriho** [romgrk/nvim-treesitter-context#47]
After deleting all other buffers except current I get this error:
```
Error detected while processing CursorMoved Autocommands for "*":
E5108: Error executing lua ...start/nvim-treesitter-context/lua/treesitter-context.lua:210: Vim(lua):E5108: Error executing lua ...start/nvim-treesitter-con
text/lua/treesitter-context.lua:181: Invalid buffer id: 2
```

Is the CursorMoved Autocommand meant to be running since I have treesiter + latest nigtly neovim installed?

**Comment by romgrk** [comment]
Yes, CursorMoved is needed. Can you provide clear reproduction steps?

**Comment by petertriho** [comment]
Oops thought I linked the other plugin I was using. https://github.com/numToStr/BufOnly.nvim

**Comment by petertriho** [comment]
Switched to another bufonly (https://github.com/schickling/vim-bufonly) plugin and it seems to not have the same issues so probably not due to this plugin
