### ISSUE TITLE
Feature request: Set winvar so that users can detect treesitter-context windows

### ISSUE THREAD

**Issue by ouuan** [romgrk/nvim-treesitter-context#50]
I hope treesitter-context can use `setwinvar` to set a winvar like "treesitter_context_key: tree_sitter_context_val" so that users can use it to filter windows.

I personally have this function in my `init.vim`, and I wish it to work with treesitter-context:

```vim
fun! s:IsOnlyWindow()
    return len(filter(getwininfo(), '!has_key(v:val.variables, "scrollview_key")')) == 1
endfun
```

**Comment by romgrk** [comment]
Done, `w:treesitter_context == v:true`.
