### ISSUE TITLE
Save Untitled buffer on quit

### ISSUE THREAD

**Issue by JoseConseco** [romgrk/nvim-treesitter-context#52]
I use this  comand : 
`:confirm qa<CR>`
To exit nvim, but with  TSContext vim is now always asking about saving changes to 'Untitled'.
I tried to add : 
`:TSContextDisable<cr> | :confirm qa<CR>`
But it still will ask about saving untitled... Is there way to kill TSContext  buffer so that I do not have to confirm saving it on q ?
btw when I run  :buffers  - I do not see this untitled buffer...

**Comment by romgrk** [comment]
Can't reproduce. Please provide more details. Context uses `nvim_create_buf` to create its scratch buffer, the doc says it's *always* `nomodified` so this shouldn't be happening. When you disable context before exiting (in a separator command), the issue disappears?

**Comment by JoseConseco** [comment]
Disabling context with  TSContextDisable - hides the popup window, but then on quit the message 'save untitled?'   is still there. When I manually create  nvim_create_buf(v:false, v:true) -  and write to this buffer, then on `confirm qa` I have no question about saving changes... I'm not sure what is going on. 
If nobody else can confirm, then maybe this is something with my config, but I do not have to test all the plugins to see which one is  in conflict.

**Comment by romgrk** [comment]
If you remove context (as in don't load it in your config), is the issue still there?

**Comment by JoseConseco** [comment]
Yes,  the problem is gone after removing context. Issue must  be related to only my config, since nobody else is confirming  it , and  I do not want to spend more time debugging it  (I already disabled few other plugins to do some testing but it did not help).

**Comment by JoseConseco** [comment]
I think I finally figured out what is going on - the conflicting plugin seems to be : 
 'mhinz/vim-startify'  + loading session  - will give 'save untitled buffer'  on session close.  
 'mhinz/vim-startify' + opening non session files  - no warning on quit
opening session ( startify - disabled) - also no problem.
I tried to disable 'VimLeavePre' autocmd in Startify but it did not affect the warning .   Anyway  I'm closing this  issue
