### ISSUE TITLE
Error detected while processing WinScrolled Autocommands for "*":

### ISSUE THREAD

**Issue by praveendhawan** [romgrk/nvim-treesitter-context#60]
Error detected while processing WinScrolled Autocommands for "*":
E5108: Error executing lua ...start/nvim-treesitter-context/lua/treesitter-context.lua:182:
'width' key must be a positive Integer

Neovim Version -
```
NVIM v0.5.0
```

System -
```
macOS Big Sur
v 11.4
```

I have a tmux session with 2 splits and neovim with two splits(with tmux zoomed in the neovim pane). As soon as I switch tmux pane, the zoomed-in pane is unzoomed and this error pops up in neovim. 
Is there any way we to avoid this issue?

![NvimTSContextError](https://user-images.githubusercontent.com/12948906/127101597-d9aabc98-1d0d-4691-bf16-9f50eb15c544.gif)

**Comment by romgrk** [comment]
Not sure why that happens, but I've added some logic to try to prevent the errors from popping up. If it persists let me know.

**Comment by praveendhawan** [comment]
It works. Thanks 👍
