### ISSUE TITLE
preserve context when on comments

### ISSUE THREAD

**Issue by tkkcc** [romgrk/nvim-treesitter-context#62]
When cursor is on comments, context window disappears. This is strange as coming from context.nvim.

For example if cursor is on the commeted line, function name disappears, but go one line up or down will show context. 
```py
def a():



    print(1)
    # print(1)
    pass
```

**Comment by romgrk** [comment]
Yeah I know. I'll see if I can find some time to fix that soon.

**Comment by JeanMertz** [comment]
For what it's worth, I also noticed that the context remains hidden if you start the cursor in a comment on a line, and then move into a non-comment area on that same line.

That is;

```lua
1 tools = {
2   autoSetHints = false, -- hidden by default, but toggleable via `<leader>i`
3   hover_with_actions = false,
4 },
```

Starting at line 3, moving back to the end of line 2 (inside the comment) makes the context disappear. Moving further to the left on line 2 into the non-comment section does not make the context appear, it only re-appears once the cursor moves over to the next line above (1), or back down (3).

Hopefully this information is useful during debugging of this issue.

**Comment by gbrlsnchs** [comment]
This also a problem for https://github.com/SmiteshP/nvim-gps (I use both this and that). Not sure if this is helpful information though, just thought it was worth mentioning.

**Comment by yanzhang0219** [comment]
Any updates for this? @romgrk 
Thank you very much.

**Comment by marcuscaisey** [comment]
I did a bit of digging last night and found the issue. I've made a PR to [nvim-treesitter/nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) https://github.com/nvim-treesitter/nvim-treesitter/pull/2729 which would allow a pretty clean fix in the code here (could just switch out `ts_utils.get_node_at_cursor()` for `ts_utils.get_node_at_cursor(0, true)`).

For now, you should be able to workaround the issue by uninstalling the `comment` parser. You might need to add `ignore_install = {'comment'}` into your treesitter configs `setup`

**Comment by rockyzhang24** [comment]
@marcuscaisey Hi, that PR in `nvim-treesitter` has been merged, so I think this issue can be solved.

**Comment by marcuscaisey** [comment]
@rockyzhang24 i'll probably get to this tomorrow

**Comment by rockyzhang24** [comment]
@marcuscaisey Thanks. As you said, we just need to change that function call. I don't have my laptop at hand so I am not able to open a PR now. So leave it to you 👊

**Comment by rockyzhang24** [comment]
I think we can use @lewis6991 's fork (https://github.com/lewis6991/nvim-treesitter-context). He cleaned the code and solved some common issues including this one.

**Comment by marcuscaisey** [comment]
nice, i'll just switch to that one for now then
