### ISSUE TITLE
Hi,you know these features good, but something need become better

### ISSUE THREAD

**Issue by 1096015776** [romgrk/nvim-treesitter-context#64]
you know that the rows in function is incorrect
maybe it is not case
but i want to let me become feel better when i use it
so could you let it become better?
I'm sorry that my english is not ok.
![截屏2021-08-19 下午5 07 24](https://user-images.githubusercontent.com/40203327/130041951-3ae341d1-2035-4d66-9872-95b2b3a7be47.png)

**Comment by zeertzjq** [comment]
I think this is a duplicate of #37.
