### ISSUE TITLE
Option to limit the height of the floating window

### ISSUE THREAD

**Issue by zeertzjq** [romgrk/nvim-treesitter-context#66]
In a C `if () ... else if () ... else if () ... else if () ... else ...` block with many branches, the floating window becomes very large, occupying over a half of the screen. An option to limit the height of the floating window can be helpful in this case.

![Screenshot_20210911_154406](https://user-images.githubusercontent.com/35768171/132940603-29e1c52f-c276-4e7d-9135-1bd85269a9a4.png)

**Comment by jakelinnzy** [comment]
Hey, what do you think about #67?

**Comment by ldelossa** [comment]
I also want this but maybe for a bit of a different reason. 

I want to use this plugin *only* to show which function I am inside. Having it show me if I'm in an "if" or a "switch" case is not very helpful to me. Would your pull @jakelinnzy accomplish this by setting the length to 1?

**Comment by zeertzjq** [comment]
Now things are getting a bit complicated, as it is not clear what to truncate.

**Comment by zeertzjq** [comment]
> I also want this but maybe for a bit of a different reason.
> 
> I want to use this plugin _only_ to show which function I am inside. Having it show me if I'm in an "if" or a "switch" case is not very helpful to me. Would your pull @jakelinnzy accomplish this by setting the length to 1?

I think it wouldn't.

**Comment by romgrk** [comment]
Closed in #67, the patterns use-case is done in d4f0193. See readme for details.
