### ISSUE TITLE
parent item is not shown in context when it's on the first line

### ISSUE THREAD

**Issue by syphar** [romgrk/nvim-treesitter-context#91]
Thanks for the awesome plugin! 

I found some strange behavior and I'm not sure where this is coming from. 

A function item that is the first line will not be shown in the context. 

I tested this with rust and python examples. 

So in a file like this: 
```python
def test():
    print("A")
    # [...] more content so the function definition is outside the screen
    print("A) # cursor here 
```
The function will not be shown in the context. 

Slightly changed like this: 

```python
# empty line here
def test():
    print("A")
    # [...] more content so the function definition is outside the screen
    print("A) # cursor here 
```

I will see the function in the context. 

I'm happy to provide more input when needed.

**Comment by syphar** [comment]
( I probably will give a shot at debugging this another day, only wanted to put it here first)

**Comment by binhtran432k** [comment]
I found the problem in the code to get parent matches. It skip the first while querying parent.
https://github.com/romgrk/nvim-treesitter-context/blob/b7d7aba81683c1cd76141e090ff335bb55332cba/lua/treesitter-context.lua#L354
I think it shoud be row >= 0 to get the first line too.
