### ISSUE TITLE
if/else pathing.  

### ISSUE THREAD

**Issue by ThePrimeagen** [romgrk/nvim-treesitter-context#99]
with `if` option on, it would could be very nice to stack the if statements that lead to this point instead of the top occurrence.  With tree sitter this could be hard due to some of the naming constraints.

If you give me some basic direction I may be able to crank this one out.

On top of that, if you have a long comment within an `else if` block (at least for the typescript) it will destroy all your context.

Here is some examples of both cases (in one example)

```typescript
if (true) {
    function foo() {


        if (false) {
            /*
                *
                *
                *
                *
                */








            const thing = 5




        } else if (true) {
            /*
                *
                *
                *
                *
                *
                *
                *
                *
                *
                *
                *
                *
                *
                *
                */
        }

        else {










            const foo = 5;








        }

    }
}
```

**Comment by syphar** [comment]
I'm guessing what you mean by _stack the if statements that lead to this point_. Also I was digging into how this works for another thing I'm working on, so here is what I think.

Are you searching for something like in this rust example?

<img width="558" alt="grafik" src="https://user-images.githubusercontent.com/540890/157490012-aee176ea-08f9-42da-a860-cc5628875d8c.png">


treesitter-context generally starts from the cursor and walks up the tree of the treesitter nodes to find the context. So when the treesitter parser shows the `else if` nodes as children to the `if` node, this plugin will pick it up. 

To give you one more example: 
In python it looks different again: 
<img width="298" alt="grafik" src="https://user-images.githubusercontent.com/540890/157490485-0c4175d1-2cbf-4653-a336-035a5261368c.png">

Which means the `else` and `elif`  nodes are both below the `if` node, but as siblings, and the `else` node is not below `elif`.  

You can use [`treesitter-playground`](https://github.com/nvim-treesitter/playground) to visualize the tree.

**Comment by ThePrimeagen** [comment]
I think the proper solution was to use rust in the first place, btw.

**Comment by ThePrimeagen** [comment]
It does appear that comments it TS are likely broken.

![Selection_214](https://user-images.githubusercontent.com/4458174/157530138-ea01c68d-e9c0-4e0a-8f73-490eb72e480f.png)

You can see ERROR and if my cursor is in a comment I lose all context.

Likely unrelated issues and specific to a language.

**Comment by ThePrimeagen** [comment]
The `else` issue, I can try to diagnose it shortly.  (could be me too)

**Comment by ThePrimeagen** [comment]
Ok turns out else was a matching problem.  My fault!

The comment thing could be reopened as a different issue.  I'll close this one down.

**Comment by syphar** [comment]
I assume https://github.com/romgrk/nvim-treesitter-context/issues/62 is what you want to create about comments
